services:
  backend:
    build: ./nestjs-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=mysql
      - DB_PASSWORD=mysql
      - DB_NAME=nestjs
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nestjs
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
